### ISSUE TITLE
Proposed roadmap

### ISSUE THREAD

**Issue by khromov** [ideag/content-cards#2]
## done
- [x] #19 rename GitHub repo to `ideag/content-cards`
- [x] #23 Fallback to `<title>` and `<meta>` if OG data not found
- [x] <del>#9 A list of popular sites not currently having native oEmbed support in WP.</del>
- [x] #15 add validation to template functions
- [x] #24 fill and update `readme.txt`
- [x] #6 Store OG data in `postmeta`, update via `WP_Cron` 
- [x] #10 Create multiple skins: for Twenty\* themes and some generic ones.
- [x] #17 Add uninstall hook for cleanup
- [x] #11  Skin detection system, similar to Themes (based on a comment block in stylesheet)
- [x] #5 TinyMCE button that prints a shortcode to to embed ANY url, not only whitelisted ones. (Right now, you'd have to add a regexp for each blog.) This is probably my most common use case, ie. wanting to link to a random blog that I'll probably never going to link to again.
- [x] #8 Allow PHP in templates. More WordPress like and more flexible.
- [x] #7 Simplified regexp rules. User would only need to enter a domain (ie. google.com) and the rest of the regexp rules get added internally. 
- [x] Checkbox to disable the default styles, or look for opengraph-oembed.css in currently active theme and if it exists, load that instead of the default. _Stylesheet now obbeys to the same logic as template files, can be overwritten in theme_
- [x] Multiple templates and css skins, for example we could make nice looking themes for the official WP themes, and some basic one, like "Light background" and "black background". _just pushed basic support for skins. Anybody care to do some actual design? ;)_

**Feel free to add more suggestions or discuss the existing ones.**

**Comment by lincourtl** [comment]
I like the idea to be able to embed any URL too. Better than that though, for my purposes, is to save the og data as a custom field into postmeta. That way it minimizes delays due to link rot and page load times waiting for embeds. 

But thank you so much Arunas for throwing together something so quick that is 90% of the way along toward what I've been seeking for years. :+1:  \* 1000

**Comment by khromov** [comment]
Great job organizing the tasks @ideag !

**Comment by ideag** [comment]
I try, I try @khromov  :)

Also, I had an idea today, that it might be nice to allow PHP in the templates. More WordPress style and more flexible.

**Comment by khromov** [comment]
@ideag Agreed that using standard PHP templates would be nice! Note sure we can use locate_template() for that since you can't pass variables to it easily. I usually just make a template function that sets up the data and uses `require` to load the template. We can still use locate_template() to find the best template before using it though.

**Comment by ideag** [comment]
So, the skins are now PHP-enabled. You can use `get_cc_data($key)` and `the_cc_data($key)` to get OpenGraph data and `the_cc_target()` to insert `target="_blank"` if it was turned on via settings / shortcode arguments.
Also, the skins are now autodetected via a header in the CSS file (not unlike plugins/themes in WordPress). The only required and used value at the moment is `Skin Name`.
