### ISSUE TITLE
Ideas for future features

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#52]
- [ ] multiple people have requested a skin where image is smaller and on the side of the text, not at the top. 
- [ ] allow people to choose the image if site provides several options [WordPress.org](https://wordpress.org/support/topic/how-can-i-change-the-look-of-content-cards?replies=2)
- [ ] "Flush cache" button to flush all cached card data.
- [ ] Cache favicon (Maybe? For consistency?)
- [x] #56 grid layout for cards [WordPress.org](https://wordpress.org/support/topic/mult-columnar-layout) - we decided to allow custom CSS classes via shortcode/filters, but not to implement grid layout ourselves.
- [x] #56 Filterable CSS classes
- [x] #55 Toggle for local image cache. I can imagine some sites don't want to cache OG images locally so being able to toggle it would be nice
- [x] Multisite support (in terms of access control. has to be discussed which was is the best to do this)

Coming from feedback on Facebook, WP.org, etc. Will be split to separate issues when/if we decide to pursue them.

**Comment by khromov** [comment]
- [ ] "Flush cache" button to flush all cached card data.
- [x] #55 Toggle for local image cache. I can imagine some sites don't want to cache OG images locally so being able to toggle it would be nice
- [x] Multisite support (in terms of access control. has to be discussed which was is the best to do this)
- [ ] Cache favicon (Maybe? For consistency?)
- [x] #56 Filterable CSS classes
