### ISSUE TITLE
v0.9.6 

### ISSUE THREAD

**Issue by ideag** [ideag/content-cards#87]
It is way, **way** past time to release a new version. There are a couple of bugs that need to be fixed and some feature requests to be considered. I'll use this ticket to keep track of all the things that need to be done for the next release.

- [x] #83 Caching setting (PR #88) 
- [x] #82 Optimize for AMP (PR #90)
- [x] #86 Conflict with other plugin due to OpenGraph class (PR #91)
- [x] #85 Custom themes for specific shortcodes (PR #95)
- [x] #84 Linkedin links
- [ ] #89 Check compatibility with Twenty Seventeen

**Comment by khromov** [comment]
Great initiative, will try to help as much as I can.

**Comment by ideag** [comment]
Looking over the open tickets I started wondering if we should do a `0.9.6` before we do a `1.0.0`. I'd love to cover all of the above for 1.0.0, but I think #69 and #67 depends on us making a switch from storing CC data in `post_meta` to a CPT (as offered in #79) or transients (your suggestion). And that touches #51 as well, probably.

And if we decide to do the switch, refactoring + a migration script = quite a big bit of work, that will probably take a while. 
Meanwhile #82 and #83 already has PR's and some kind of solutions for #86 #85 #89 are also quite doable over this weekend, and there is no reason to keep them unreleased. 

What do you think, @khromov ?

**Comment by ideag** [comment]
Thanks for all the prompt replies on the support forum @khromov. I really need to get better at doing support. Any thoughts about the `0.9.6` vs `.1.0.0.´? Image caching is currently proving to cause more problems that it is worth, probably. So it might be a good idea to nix it until we solve it properly.

**Comment by khromov** [comment]
@ideag Not opposed to that. I think that we should ship a mechanism for deleting old cached images in the media library for `0.9.6`, so that people can revert to no image caching easily. I'll have some time this weekend to look into that.

Image caching right now seems to have a particularly nasty bug with the "infinite loop" image download. I've been over the code a lot and can't find it, I'm thinking either object cache issue or something with hook/filter invocation order, but I'm very much for disabling it for now and also have a way to clean up existing sites.

**Comment by ideag** [comment]
Alright, if you could tackle the image cleanup script, we could release the `0.9.6` next Monday. And we'll move #69 #67 to `1.0.0` (i'll make a separate issue for that). I also think it must be object caching interfering somehow, otherwise it would be a much more widespread issue.
